#api conncection
api_service_name = "youtube"
api_version = "v3"
api_key = "AIzaSyA5lfDN1q8WHw9v1mvZiWaCb4OXyES8BB8"

#database
host="localhost"
user="helen1"
password="123456"
database="youtubedataharvesting"